parameters:
#    cygnus_doctrine_magic_embed.example.class: Cygnus\DoctrineMagicEmbedBundle\Example

services:
#    cygnus_doctrine_magic_embed.example:
#        class: %cygnus_doctrine_magic_embed.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
